import streamlit as st
from PIL import Image
import tempfile

from app.detector.model import AIDetector


st.set_page_config(
    page_title="AI Image Authenticity Detector",
    page_icon="🤖",
    layout="centered",
)


@st.cache_resource
def load_detector():
    """Load the full ensemble detector once."""
    return AIDetector()


def main():
    st.title("AI Image Authenticity Detector")
    st.caption("Created by Syed Hissam Kazmi")
    st.markdown(
        "Upload an image to estimate the probability that it was generated by AI."
    )

    uploaded_file = st.file_uploader(
        "Choose an image...",
        type=["jpg", "jpeg", "png", "webp"],
    )

    if uploaded_file is None:
        st.info("Please upload an image to begin.")
        return

    try:
        image = Image.open(uploaded_file).convert("RGB")
    except Exception:
        st.error("Could not open the image. Please upload a valid image file.")
        return

    st.image(image, use_container_width=True, caption="Uploaded Image")

    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
        image.save(tmp.name)
        tmp_path = tmp.name

    detector = load_detector()

    with st.spinner("Analyzing image..."):
        result = detector.predict_detailed(tmp_path)

    if result is None or result.get("ensemble") is None:
        st.error("AI detector is currently unavailable. Please try again later.")
        return

    ai_prob = result["ensemble"]
    human_prob = 1.0 - ai_prob

    st.markdown("---")
    st.subheader("Analysis Result")

    col1, col2 = st.columns(2)
    col1.metric("AI Probability", f"{ai_prob:.2%}")
    col2.metric("Human Probability", f"{human_prob:.2%}")

    confidence = result.get("confidence")
    if confidence:
        if confidence == "HIGH":
            st.error(f"Confidence: {confidence}")
        elif confidence == "MEDIUM":
            st.warning(f"Confidence: {confidence}")
        else:
            st.info(f"Confidence: {confidence}")

    models = result.get("models", {})
    if models:
        st.subheader("Model Predictions")
        for model_name, prob in models.items():
            st.write(f"**{model_name}**: {prob:.2%}")

    signals = result.get("signals", [])
    if signals:
        st.subheader("Signals")
        for signal in signals:
            st.write(f"• {signal}")

    colors = result.get("dominant_colors", [])
    if colors:
        st.subheader("Dominant Colours")
        color_html = " ".join(
            f'<span style="display:inline-block;width:24px;height:24px;background:{c};border-radius:4px;margin-right:5px;"></span>'
            for c in colors
        )
        st.markdown(color_html, unsafe_allow_html=True)

    st.caption(
        "This result is probabilistic and should not be treated as definitive proof."
    )


if __name__ == "__main__":
    main()